# Generated by Django 5.1.2 on 2024-10-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=500)),
                ('shortened_url', models.CharField(blank=True, max_length=10, unique=True)),
            ],
        ),
    ]
